import Head from 'next/head'
import About from '../components/About'
import HeroText from '../components/HeroText'
import MyWork from '../components/myWork'
import Navbar from '../components/Navbar'
import SkillsAndTools from '../components/SkillsAndTools'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <HeroText />
      <About />
      <SkillsAndTools />
      <MyWork />
    </div>
  )
}
